title:              Arjun Nair
email:              arjuninstil@gmail.com
description:        My Data Science Portfolio
author:             Arjun Nair
baseurl:            ""
url:                "https://arjuninstil.github.io"

# Social Profiles
twitter_username:   
github_username: arjuninstil
facebook_username:  
instagram_username: ya_rjun
linkedin_username: arjunnairb

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
